language: node_js
node_js: node
services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server
deploy:
  provider: heroku
  api_key:
    secure: PpvhstrhTv1ShJWNqoSkAaF3myrGooXqIi/xBk98jLjh9DBGv9xgOyTlDNwmSVG5QLcn5bD2xBTTNvEScBItBzVqqyNW0F338mXFAcWusNP6F+rN4M71AneW9W4cw8zntSgZe2Bjti58lXW9Q1Lf/fTWxBd3idlKF2HDJ4v7tmfcxLWdO9BCBOmzCisvwsoQAW3W+BHCBG/DwDSWFC4o+p1EVZfT7R1gLWLEulM3nrQ36dUpWMAHRKAcTMmJ2Ci6ZyQWGgLCOPM0Zmnf7CaBrRpxn7TIueuxzotI99kQAjDIqsnH5UU1XDSsX1FqexgwFwom0zBeHvGjpp6VAiGTPmL+MNjqwl74zsAt9Ze76nzfgh5/o7hMVJo9L7YdPnqqYebRZ0woZifE5kq423rCXju1Ji96cfz3M4+ImXyXafLsgNnhmsCNjnp1fzeZSCLlQTombXZq29Fjn08AFxgBPG7pPreCBJKeX6wMf/yHDTX537+gzx3vKnHFJKGoDQsuVTQ9Ej7DuJQoJ1xSbjy41LuYvlkZutUYTjh377pyKpwtT2l2p6ScLEGd8qKLYgiCd+hQ9XnjLvM1tqM3t8yhlcK+knQCwt/HX6ZfDOTMNrBwmaUIclJKU8iLNI80NjC3l9tdFfOAxdnVbuQ2fEWv56BnngJr5e52ZHVMzZ1fLok=
  app: hidden-castle-45525
  on:
    repo: dotexe0/mongo-shopping-list
